# Generated by Django 4.2.15 on 2025-11-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingredient_recipe_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='core.ingredient'),
        ),
    ]
